### PR TITLE
Added Kamesh Photo from Pod 2.1.1

### PR DESCRIPTION
**Pull request by ksdkamesh99**
Added My Photo from Pod 2.1.1

Kindly Review and Merge

### CODE REVIEW

**Review by wrussell1999 — CHANGES_REQUESTED** [review]
Can you crop this to a square please?

**Comment by wrussell1999** [comment]
@ksdkamesh99 bump

**Comment by ksdkamesh99** [comment]
@wrussell1999 Sorry for the delay. I messed up with other works. Any way kindly review my PR and Merge

**Review by wrussell1999 — APPROVED** [review]
Excellent thanks!

**Pull request merged**
